#!/usr/bin/php
<?php

$users = <<<sql
CREATE TABLE users
(
    user_id bigint(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_email varchar(100) NOT NULL,
    user_username varchar(100) NOT NULL,
    user_password varchar(100) NOT NULL,
    user_name varchar(100) NOT NULL,
    user_lastname_1 varchar(100),
    user_lastname_2 varchar(100),
    user_company varchar(100),
    user_business_name varchar(100),
    user_business_position varchar(100),
    user_business_phone varchar(100),
    user_whatsapp varchar(100),
    user_status bit(1) DEFAULT b'1' NOT NULL
);
CREATE UNIQUE INDEX users_user_email_uindex ON users (user_email);
CREATE UNIQUE INDEX users_user_username_uindex ON users (user_username);
sql;

$complaints = <<<sql
CREATE TABLE complaints
(
    complaint_id bigint(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id bigint(20) NOT NULL,
    topic_id bigint(20),
    complaint_message varchar(255) NOT NULL,
    complaint_date timestamp DEFAULT CURRENT_TIMESTAMP,
    complaint_status bit(1) DEFAULT b'1' NOT NULL
);
sql;

$payers = <<<sql
CREATE TABLE payers
(
    payer_id bigint(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    payer_name varchar(100) NOT NULL,
    payer_status bit DEFAULT b'1' NOT NULL
);
sql;

$topics=<<<sql
CREATE TABLE topics
(
    topic_id int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    topic_name varchar(100) NOT NULL,
    topic_status bit(1) DEFAULT b'1'
);
sql;


require "libs/database.php";
db_query($users);
db_query($complaints);
db_query($payers);
db_query($topics);